@startuml

class App {
  +output(out:String):void
  +outputString(result:ArrayList<String>, filenameout:string):string
  +sort(filename:String):ArrayList<String>
  +main(String [] args):void
}

@enduml